# Generated by Django 5.2 on 2025-05-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_appointment_doctor_appointment_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
